### ISSUE TITLE
running control.s3_bucket_untagged against multiple aws accounts

### ISSUE THREAD

**Issue by judell** [turbot/steampipe-mod-aws-tags#6]
I have two AWS accounts, call them jon-personal and jon-public. I can query them both by their names in my aws.spc. For the mod, though, it seems I need to reduce the aws.spc to a single uncommented entry in order to run control.s3_bucket_untagged, is that expected?

**Comment by e-gineer** [comment]
Yes, it's expected. The mods are designed to run against the first schema in the search path. Suggestions:
* Use an aggregator, which combines the accounts.
* Use the `--search-path-prefix` CLI option to set your desired target.

It's important that mods are schema agnostic so they work for different people, which is why we use this search path approach.

**Comment by cbruno10** [comment]
Closing issue as I believe it's been answered above, @judell , please re-open if not though, thanks!
